-- LLM token counter / cost calculator data. Generated by scripts/llm-seed-sql.mjs.
-- Edit a row (price, is_active, notes) and the tool picks it up without a deploy.
create table if not exists llm_models (
  slug text primary key,
  provider text not null,
  display_name text not null,
  tokenizer text not null,
  context_window int,
  input_per_1m numeric not null,
  output_per_1m numeric not null,
  cached_input_per_1m numeric,
  is_active boolean default true,
  notes text,
  updated_at timestamptz default now()
);
alter table llm_models enable row level security;
drop policy if exists "public read" on llm_models;
create policy "public read" on llm_models for select to anon using (true);

create table if not exists llm_price_history (
  id bigserial primary key,
  slug text references llm_models(slug) on delete cascade,
  input_per_1m numeric,
  output_per_1m numeric,
  changed_at timestamptz default now()
);
alter table llm_price_history enable row level security;
drop policy if exists "public read" on llm_price_history;
create policy "public read" on llm_price_history for select to anon using (true);

-- Every insert or price change also lands in the history table, and bumps updated_at.
create or replace function llm_models_track() returns trigger language plpgsql as $$
begin
  if tg_op = 'INSERT' or new.input_per_1m is distinct from old.input_per_1m or new.output_per_1m is distinct from old.output_per_1m then
    insert into llm_price_history (slug, input_per_1m, output_per_1m) values (new.slug, new.input_per_1m, new.output_per_1m);
  end if;
  new.updated_at = now();
  return new;
end $$;
drop trigger if exists llm_models_track on llm_models;
create trigger llm_models_track before insert or update on llm_models for each row execute function llm_models_track();

insert into llm_models (slug, provider, display_name, tokenizer, context_window, input_per_1m, output_per_1m, cached_input_per_1m, is_active, notes) values
  ('claude-fable-5-1', 'Anthropic', 'Claude Fable 5.1', 'o200k_base', 1000000, 10, 50, 0.25, true, 'Fable 5.1 is the most expensive Claude model in the public price list, at $10 per million input tokens and $50 per million output. Its cache-read price is unusually low — 2.5% of the base input rate, or $0.25 per million — so a large, stable prompt that is reused across many calls costs far less than the headline rate suggests. Anthropic notes that Claude 4.7 and later models use a newer tokenizer that produces roughly 30% more tokens for the same text than earlier Claude models, so a prompt counted here with a generic encoding is likely to be billed higher on this model.'),
  ('claude-opus-5-5', 'Anthropic', 'Claude Opus 5.5', 'o200k_base', 1000000, 4, 20, 0.2, true, 'Opus 5.5 is priced at $4 per million input tokens and $20 per million output, below the $5 and $25 charged for Opus 5 and the 4.x Opus line. Cache reads are 5% of the base input price ($0.20 per million), and Anthropic lists a separate fast mode for Opus models at premium prices ($8 input, $40 output for Opus 5.5) that this calculator does not model. It uses the newer Claude tokenizer, which Anthropic says yields about 30% more tokens than earlier Claude models.'),
  ('claude-opus-5', 'Anthropic', 'Claude Opus 5', 'o200k_base', 1000000, 5, 25, 0.5, true, null),
  ('claude-sonnet-5', 'Anthropic', 'Claude Sonnet 5', 'o200k_base', 1000000, 2, 10, 0.2, true, 'Sonnet 5 launched at introductory prices of $2 per million input tokens and $10 per million output, and Anthropic has since confirmed these are now the standard price: the increase to $3 and $15 that had been scheduled for 1 September 2026 will not happen. That makes it one of the cheapest 1M-context models from Anthropic. Cache reads cost $0.20 per million, and it uses the newer tokenizer that produces around 30% more tokens than Claude models up to Sonnet 4.6.'),
  ('claude-sonnet-4-6', 'Anthropic', 'Claude Sonnet 4.6', 'o200k_base', 1000000, 3, 15, 0.3, true, null),
  ('claude-haiku-4-5', 'Anthropic', 'Claude Haiku 4.5', 'o200k_base', 200000, 1, 5, 0.1, true, 'Haiku 4.5 is the low-cost Claude option at $1 per million input tokens and $5 per million output, with cache reads at $0.10 per million. It has a 200,000-token context window, smaller than the 1M windows of the newer Claude models, and it still uses the earlier Claude tokenizer, so token counts for the same text are lower than on Claude 4.7 and later.'),
  ('gpt-6-astra', 'OpenAI', 'GPT-6 Astra', 'o200k_base', null, 10, 50, 1, true, null),
  ('gpt-6-sol', 'OpenAI', 'GPT-6 Sol', 'o200k_base', null, 2, 10, 0.2, true, 'GPT-6 Sol sits in the middle of OpenAI’s GPT-6 line at $2 per million input tokens and $10 per million output, with cached input at $0.20 per million — a 90% discount on repeated prompt prefixes. OpenAI has not published a tokenizer specifically for this model, so the counts shown here use o200k_base, the encoding used by the GPT-4o and GPT-4.1 families, and should be treated as an estimate.'),
  ('gpt-6-luna', 'OpenAI', 'GPT-6 Luna', 'o200k_base', null, 0.1, 0.5, 0.01, true, null),
  ('gpt-5-6-sol', 'OpenAI', 'GPT-5.6 Sol', 'o200k_base', null, 4, 20, 0.4, true, 'GPT-5.6 Sol is the top model of the GPT-5.6 family at $4 per million input tokens and $20 per million output, with cached input at $0.40 per million. Counts here use o200k_base as an estimate.'),
  ('gpt-5-6-terra', 'OpenAI', 'GPT-5.6 Terra', 'o200k_base', null, 2, 12, 0.2, true, null),
  ('gpt-5-6-luna', 'OpenAI', 'GPT-5.6 Luna', 'o200k_base', null, 0.2, 1.2, 0.02, true, null),
  ('gpt-5-5', 'OpenAI', 'GPT-5.5', 'o200k_base', null, 5, 30, 0.5, true, null),
  ('gpt-5-4-mini', 'OpenAI', 'GPT-5.4 mini', 'o200k_base', null, 0.75, 4.5, 0.075, true, null),
  ('gpt-5-mini', 'OpenAI', 'GPT-5 mini', 'o200k_base', 400000, 0.25, 2, 0.025, true, null),
  ('gpt-5-nano', 'OpenAI', 'GPT-5 nano', 'o200k_base', 400000, 0.05, 0.4, 0.005, true, null),
  ('gpt-4-1', 'OpenAI', 'GPT-4.1', 'o200k_base', 1047576, 2, 8, 0.5, true, 'GPT-4.1 is priced at $2 per million input tokens and $8 per million output, with cached input at $0.50 per million (a 75% discount). Its context window is about a million tokens, which is why a whole codebase or book can fit in one prompt. It uses o200k_base, so the counts on this page are exact for it.'),
  ('gpt-4o', 'OpenAI', 'GPT-4o', 'o200k_base', 128000, 2.5, 10, 1.25, true, 'GPT-4o costs $2.50 per million input tokens and $10 per million output, and its cached-input price of $1.25 is a 50% discount — a much smaller reduction than the 90% offered on newer OpenAI models, so caching saves less here. GPT-4o uses the o200k_base encoding and has a 128,000-token context window, so the token counts on this page are exact for it rather than estimates.'),
  ('gpt-4o-mini', 'OpenAI', 'GPT-4o mini', 'o200k_base', 128000, 0.15, 0.6, 0.075, true, null),
  ('gemini-3-8-flash', 'Google', 'Gemini 3.8 Flash', 'o200k_base', 1000000, 0.75, 3.75, 0.075, true, 'Promotional price through 31 December 2026; Google lists an increase from 1 January 2027.'),
  ('gemini-3-5-flash', 'Google', 'Gemini 3.5 Flash', 'o200k_base', 1000000, 1.5, 9, 0.15, true, 'Gemini 3.5 Flash costs $1.50 per million input tokens and $9 per million output, with cached input at $0.15 per million and a 1M-token context window. Google’s listed prices apply to prompts up to 200,000 tokens; longer prompts are billed at a higher tier that this calculator does not model. Google does not publish its tokenizer for browsers, so counts here are estimates made with o200k_base.'),
  ('gemini-3-5-flash-lite', 'Google', 'Gemini 3.5 Flash-Lite', 'o200k_base', 1000000, 0.3, 2.5, 0.03, true, null),
  ('gemini-3-1-pro-preview', 'Google', 'Gemini 3.1 Pro Preview', 'o200k_base', 200000, 2, 12, 0.2, true, null),
  ('gemini-2-5-pro', 'Google', 'Gemini 2.5 Pro', 'o200k_base', 1000000, 1.25, 10, 0.125, true, 'Gemini 2.5 Pro is priced at $1.25 per million input tokens and $10 per million output, with cached input at $0.125 per million. The figures apply to prompts up to 200,000 tokens; beyond that Google charges a higher rate, which matters if you fill the 1M-token window. Token counts here are estimates using o200k_base rather than Google’s own tokenizer.'),
  ('gemini-2-5-flash', 'Google', 'Gemini 2.5 Flash', 'o200k_base', 1000000, 0.3, 2.5, 0.03, true, null),
  ('gemini-2-5-flash-lite', 'Google', 'Gemini 2.5 Flash-Lite', 'o200k_base', 1000000, 0.1, 0.4, 0.01, true, null)
on conflict (slug) do update set
  provider = excluded.provider, display_name = excluded.display_name, tokenizer = excluded.tokenizer,
  context_window = excluded.context_window, input_per_1m = excluded.input_per_1m,
  output_per_1m = excluded.output_per_1m, cached_input_per_1m = excluded.cached_input_per_1m,
  notes = excluded.notes;
