-- Rich-result eligibility per schema type. Generated by scripts/schema-seed-sql.mjs.
-- When Google changes what it supports, update the row (and verified_on) here and
-- the warning on the generator page changes without a deploy.
create table if not exists schema_type_status (
  slug text primary key,
  rich_result_eligible boolean not null,
  google_notes text,
  docs_url text,
  verified_on date not null
);
alter table schema_type_status enable row level security;
drop policy if exists "public read" on schema_type_status;
create policy "public read" on schema_type_status for select to anon using (true);

insert into schema_type_status (slug, rich_result_eligible, google_notes, docs_url, verified_on) values
  ('faq', false, 'Google now shows FAQ rich results only for well-known, authoritative government and health websites. Markup on other sites is valid and harmless, but should not be expected to produce a rich result.', 'https://developers.google.com/search/docs/appearance/structured-data/faqpage', '2026-09-24'),
  ('local-business', true, 'Google uses LocalBusiness markup for business details in the knowledge panel, alongside your Business Profile. It is not a standalone rich result, and it does not replace a Google Business Profile.', 'https://developers.google.com/search/docs/appearance/structured-data/local-business', '2026-09-24'),
  ('product', true, 'Product markup can produce product snippets (rating, price and availability in the result) and merchant listing experiences. Merchant listings need a page where the product can be bought, and stricter fields.', 'https://developers.google.com/search/docs/appearance/structured-data/product-snippet', '2026-09-24'),
  ('article', true, 'Article markup has no required properties. It helps Google understand the headline, images, dates and author of a news, sports or blog article, and can influence the title, image and date shown for it in results.', 'https://developers.google.com/search/docs/appearance/structured-data/article', '2026-09-24'),
  ('event', true, 'Event markup can make an event eligible for an event experience in Google Search, with dates, venue and ticket links. Google requires a name, a start date and a location.', 'https://developers.google.com/search/docs/appearance/structured-data/event', '2026-09-24'),
  ('recipe', true, 'Recipe markup can make a recipe eligible for a rich result with image, rating, cooking time and calories, and for the recipe carousel. Google requires a name and an image.', 'https://developers.google.com/search/docs/appearance/structured-data/recipe', '2026-09-24'),
  ('howto', false, 'Google removed HowTo rich results from Search on desktop and mobile in September 2023 and retired its documentation, so this markup no longer changes how a result looks in Google. It remains valid schema.org and other systems may still read it.', 'https://developers.google.com/search/blog/2023/08/howto-faq-changes', '2026-09-24'),
  ('breadcrumb', true, 'Breadcrumb markup lets Google show a page’s position in the site hierarchy in its result. Google needs at least two breadcrumbs, each with a name and a position.', 'https://developers.google.com/search/docs/appearance/structured-data/breadcrumb', '2026-09-24'),
  ('organization', true, 'Organization markup helps Google understand your organization and can influence details such as the logo and name in results and the knowledge panel. Google lists no required properties and recommends adding as many relevant ones as you can.', 'https://developers.google.com/search/docs/appearance/structured-data/organization', '2026-09-24'),
  ('video', true, 'VideoObject markup can make a video eligible for video rich results, key moments and a LIVE badge for livestreams. Google requires a name, a thumbnail and an upload date.', 'https://developers.google.com/search/docs/appearance/structured-data/video', '2026-09-24'),
  ('job-posting', true, 'JobPosting markup makes a job eligible for Google’s job search experience. Google requires a title, description, posting date, hiring organization and job location (or, for remote jobs, applicant location requirements).', 'https://developers.google.com/search/docs/appearance/structured-data/job-posting', '2026-09-24')
on conflict (slug) do update set
  rich_result_eligible = excluded.rich_result_eligible, google_notes = excluded.google_notes,
  docs_url = excluded.docs_url, verified_on = excluded.verified_on;
