-- Salaried-individual income tax by tax year. Generated by scripts/tax-seed-sql.mjs.
-- Update a slab or flip is_current in the Supabase dashboard and the calculator
-- picks it up without a deploy. Always keep source_url and verified_on truthful:
-- they are shown publicly on the page.
create table if not exists tax_years (
  id text primary key,
  country text not null,
  label text not null,
  effective_from date,
  effective_to date,
  is_current boolean default false,
  source_url text not null,
  verified_on date not null,
  slabs jsonb not null,      -- [{min, max, rate, fixed}]  tax = fixed + rate * (income - min)
  rules jsonb not null       -- {surcharge: {rate, threshold} | null, notes, sourceName, taxYearName}
);
alter table tax_years enable row level security;
drop policy if exists "public read" on tax_years;
create policy "public read" on tax_years for select to anon using (true);

insert into tax_years (id, country, label, effective_from, effective_to, is_current, source_url, verified_on, slabs, rules) values
  ('pk-2026-27', 'Pakistan', 'Tax Year 2026-27', '2026-07-01', '2027-06-30', true, 'https://fbr.gov.pk/Budget2026-27/FinanceBill/Finance-Bill-2026.pdf', '2026-09-24',
    '[{"min":0,"max":600000,"rate":0,"fixed":0},{"min":600000,"max":1200000,"rate":0.01,"fixed":0},{"min":1200000,"max":2200000,"rate":0.11,"fixed":6000},{"min":2200000,"max":3200000,"rate":0.2,"fixed":116000},{"min":3200000,"max":4100000,"rate":0.25,"fixed":316000},{"min":4100000,"max":5600000,"rate":0.29,"fixed":541000},{"min":5600000,"max":7000000,"rate":0.32,"fixed":976000},{"min":7000000,"max":null,"rate":0.35,"fixed":1424000}]'::jsonb,
    '{"surcharge":null,"notes":"The 9% surcharge on income above Rs 10 million is removed for this tax year.","sourceName":"Finance Bill 2026 (published by FBR), First Schedule Part I Division I clause (2) and section 4AB","taxYearName":"Tax Year 2027"}'::jsonb),
  ('pk-2025-26', 'Pakistan', 'Tax Year 2025-26', '2025-07-01', '2026-06-30', false, 'https://download1.fbr.gov.pk/Docs/2025881983148210Income-Tax-Ordinance,-2001-Amended-upto-31.07.2025.pdf', '2026-09-24',
    '[{"min":0,"max":600000,"rate":0,"fixed":0},{"min":600000,"max":1200000,"rate":0.01,"fixed":0},{"min":1200000,"max":2200000,"rate":0.11,"fixed":6000},{"min":2200000,"max":3200000,"rate":0.23,"fixed":116000},{"min":3200000,"max":4100000,"rate":0.3,"fixed":346000},{"min":4100000,"max":null,"rate":0.35,"fixed":616000}]'::jsonb,
    '{"surcharge":{"rate":0.09,"threshold":10000000},"notes":"A 9% surcharge on the income tax applies where taxable income exceeds Rs 10 million (salaried individuals).","sourceName":"Income Tax Ordinance 2001 (FBR edition amended up to 31 July 2025), First Schedule Part I Division I clause (2) and section 4AB","taxYearName":"Tax Year 2026"}'::jsonb),
  ('pk-2024-25', 'Pakistan', 'Tax Year 2024-25', '2024-07-01', '2025-06-30', false, 'https://download1.fbr.gov.pk/Docs/2024751675120641IncomeTaxOrdinance,2001-amended-upto30.06.2024.pdf', '2026-09-24',
    '[{"min":0,"max":600000,"rate":0,"fixed":0},{"min":600000,"max":1200000,"rate":0.05,"fixed":0},{"min":1200000,"max":2200000,"rate":0.15,"fixed":30000},{"min":2200000,"max":3200000,"rate":0.25,"fixed":180000},{"min":3200000,"max":4100000,"rate":0.3,"fixed":430000},{"min":4100000,"max":null,"rate":0.35,"fixed":700000}]'::jsonb,
    '{"surcharge":{"rate":0.1,"threshold":10000000},"notes":"A 10% surcharge on the income tax applies where taxable income exceeds Rs 10 million.","sourceName":"Income Tax Ordinance 2001 (FBR edition amended up to 30 June 2024), First Schedule Part I Division I clause (2) and section 4AB","taxYearName":"Tax Year 2025"}'::jsonb)
on conflict (id) do update set
  label = excluded.label, effective_from = excluded.effective_from, effective_to = excluded.effective_to,
  is_current = excluded.is_current, source_url = excluded.source_url, verified_on = excluded.verified_on,
  slabs = excluded.slabs, rules = excluded.rules;
