import {
  datetime, list, prune, repeater, select, text, textarea, url, asList, oneOrMany,
} from '../core.js';

export default {
  slug: 'article',
  pageSlug: 'article-schema-generator',
  name: 'Article',
  label: 'Article',
  previewKind: 'article',
  status: {
    richResult: 'eligible',
    googleNotes: 'Article markup has no required properties. It helps Google understand the headline, images, dates and author of a news, sports or blog article, and can influence the title, image and date shown for it in results.',
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/article',
    verifiedOn: '2026-09-24',
  },
  fields: [
    select('articleType', 'Article type', { options: ['Article', 'NewsArticle', 'BlogPosting'], help: 'NewsArticle for news, BlogPosting for blog posts, Article for anything else.' }),
    text('headline', 'Headline', { recommended: true, maxLength: 110, placeholder: 'How we cut our page load time by 40%' }),
    textarea('description', 'Description', { help: 'A short summary of the article.' }),
    list('image', 'Image URLs', { recommended: true, itemType: 'url', help: 'One URL per line. Google recommends several high-resolution images (at least 50,000 pixels) in 16:9, 4:3 and 1:1.' }),
    datetime('datePublished', 'Date published', { recommended: true, tzRecommended: true, placeholder: '2026-03-18T09:00:00+05:00' }),
    datetime('dateModified', 'Date modified', { recommended: true, tzRecommended: true, placeholder: '2026-04-02T14:30:00+05:00' }),
    repeater('authors', 'Authors', [
      select('type', 'Type', { options: ['Person', 'Organization'] }),
      text('name', 'Name', { help: 'Only the name: no job title, honorific or publisher.' }),
      url('url', 'Author page URL', { help: 'A page that uniquely identifies the author.' }),
    ], { recommended: true, itemLabel: 'Author', help: 'List each author separately.' }),
    text('publisherName', 'Publisher name'),
    url('publisherLogo', 'Publisher logo URL'),
    url('mainEntityOfPage', 'Canonical page URL', { help: 'The URL of the page this article lives on.' }),
  ],
  build: (v) => prune({
    '@context': 'https://schema.org',
    '@type': v.articleType || 'Article',
    headline: v.headline,
    description: v.description,
    image: oneOrMany(asList(v.image)),
    datePublished: v.datePublished,
    dateModified: v.dateModified,
    author: (v.authors || []).filter((a) => a.name).map((a) => ({ '@type': a.type || 'Person', name: a.name, url: a.url })),
    publisher: v.publisherName ? { '@type': 'Organization', name: v.publisherName, logo: v.publisherLogo ? { '@type': 'ImageObject', url: v.publisherLogo } : undefined } : undefined,
    mainEntityOfPage: v.mainEntityOfPage ? { '@type': 'WebPage', '@id': v.mainEntityOfPage } : undefined,
  }),
  example: {
    articleType: 'BlogPosting',
    headline: 'How we cut our page load time by 40%',
    description: 'A step-by-step account of the changes that made our site faster.',
    image: ['https://example.com/img/page-speed-16x9.jpg', 'https://example.com/img/page-speed-4x3.jpg', 'https://example.com/img/page-speed-1x1.jpg'],
    datePublished: '2026-03-18T09:00:00+05:00',
    dateModified: '2026-04-02T14:30:00+05:00',
    authors: [{ type: 'Person', name: 'Amina Rahman', url: 'https://example.com/authors/amina-rahman' }],
    publisherName: 'Example Engineering',
    publisherLogo: 'https://example.com/img/logo-600x60.png',
    mainEntityOfPage: 'https://example.com/blog/page-load-40-percent',
  },
  copy: {
    keyword: 'article schema generator',
    lead: 'This article schema generator creates valid Article, NewsArticle or BlogPosting JSON-LD from your headline, images, dates and authors, with each field checked against ISO 8601 and Google’s recommendations as you type.',
    tableIntro: 'Google lists no required properties for Article markup: every property is recommended. That makes it easy to publish a thin, low-value block, so the table separates the ones that matter most from the optional extras.',
    mistakes: [
      'A headline that is too long. Google may truncate long titles, and the headline property is meant to be concise; keep it under about 110 characters.',
      'Putting more than the name in the author field — for example “Dr Amina Rahman, Senior Editor at Example News”. Use only the name, and put a separate author for each person.',
      'Dates without a time zone. ISO 8601 dates with a UTC offset, such as 2026-03-18T09:00:00+05:00, remove any ambiguity about when the article was published.',
      'Setting dateModified to today on every visit. It should change only when the content actually changes.',
      'Choosing NewsArticle for content that is not news. Use BlogPosting for blog posts and Article as a general fallback.',
      'Images that are not crawlable or are smaller than the recommended size. An image should represent the article and be indexable.',
    ],
    notes: [
      'Article markup is the most widely used structured data type, but it is also the one with the least visible effect. Google describes it as helping the search engine understand the page and display better title text, images and date information; it does not usually produce a distinct rich result of its own.',
      'The properties that matter most are the ones about identity and freshness: who wrote it, when it was first published and when it last changed. Consistent, honest values for those help Google connect authors across your site and show accurate dates.',
    ],
    example: 'A blog post with three image ratios, both dates with time zones, an author and a publisher, as generated on this page, is shown below.',
    faqs: [
      { q: 'Which properties are required for Article schema?', a: 'None. Google lists author, dateModified, datePublished, headline and image as recommended, and asks that you include as many as apply.' },
      { q: 'What is the difference between Article, NewsArticle and BlogPosting?', a: 'NewsArticle is for news, BlogPosting is for blog posts, and Article is the general type. NewsArticle and BlogPosting are subtypes of Article, so they accept the same properties.' },
      { q: 'What date format should I use?', a: 'ISO 8601, ideally with a time zone offset, such as 2026-03-18T09:00:00+05:00 or 2026-03-18T04:00:00Z.' },
      { q: 'How many authors can I list?', a: 'As many as wrote the article. Give each author their own entry rather than combining names in one field.' },
      { q: 'Does Article schema improve rankings?', a: 'Google does not say that it is a ranking factor. It helps Google understand and present the page, which can influence how the result looks.' },
    ],
  },
};
