import {
  country, date, email, group, list, phone, prune, repeater, select, text, textarea, url, asList, oneOrMany,
} from '../core.js';

export default {
  slug: 'organization',
  pageSlug: 'organization-schema-generator',
  name: 'Organization',
  label: 'Organization',
  previewKind: 'organization',
  status: {
    richResult: 'eligible',
    googleNotes: 'Organization markup helps Google understand your organization and can influence details such as the logo and name in results and the knowledge panel. Google lists no required properties and recommends adding as many relevant ones as you can.',
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/organization',
    verifiedOn: '2026-09-24',
  },
  fields: [
    select('orgType', 'Organization type', { options: ['Organization', 'Corporation', 'NGO', 'EducationalOrganization', 'GovernmentOrganization', 'OnlineStore', 'NewsMediaOrganization'] }),
    text('name', 'Name', { recommended: true, placeholder: 'Example Ltd', help: 'The name people know you by, matching your site name.' }),
    text('legalName', 'Legal name', { help: 'Only if different from the name.' }),
    url('url', 'Website URL', { recommended: true, placeholder: 'https://example.com', help: 'The URL that identifies your organization.' }),
    url('logo', 'Logo URL', { recommended: true, placeholder: 'https://example.com/logo.png', help: 'At least 112×112 pixels, crawlable, and legible on a white background.' }),
    textarea('description', 'Description'),
    date('foundingDate', 'Founding date', { placeholder: '2015-04-01' }),
    email('email', 'Email'),
    phone('telephone', 'Telephone', { placeholder: '+1 555 010 2030' }),
    group('address', 'Address', [
      text('streetAddress', 'Street address'),
      text('addressLocality', 'City'),
      text('addressRegion', 'State or region'),
      text('postalCode', 'Postal code'),
      country('addressCountry', 'Country code', { placeholder: 'US' }),
    ], { recommended: true }),
    repeater('contactPoints', 'Contact points', [
      select('contactType', 'Type', { options: ['customer service', 'technical support', 'sales', 'billing support', 'press'] }),
      phone('telephone', 'Telephone'),
      email('email', 'Email'),
      text('areaServed', 'Area served', { placeholder: 'US' }),
      text('availableLanguage', 'Language', { placeholder: 'English' }),
    ], { itemLabel: 'Contact point' }),
    list('sameAs', 'Profile URLs (sameAs)', { itemType: 'url', help: 'Social profiles, Wikipedia or Wikidata pages and other pages about you, one per line.' }),
  ],
  build: (v) => prune({
    '@context': 'https://schema.org',
    '@type': v.orgType || 'Organization',
    name: v.name,
    legalName: v.legalName,
    url: v.url,
    logo: v.logo,
    description: v.description,
    foundingDate: v.foundingDate,
    email: v.email,
    telephone: v.telephone,
    address: v.address && Object.values(v.address).some(Boolean) ? { '@type': 'PostalAddress', ...v.address } : undefined,
    contactPoint: (v.contactPoints || []).filter((c) => c.telephone || c.email).map((c) => ({
      '@type': 'ContactPoint', contactType: c.contactType, telephone: c.telephone, email: c.email, areaServed: c.areaServed, availableLanguage: c.availableLanguage,
    })),
    sameAs: oneOrMany(asList(v.sameAs)),
  }),
  example: {
    orgType: 'Organization',
    name: 'Example Ltd',
    legalName: 'Example Limited',
    url: 'https://example.com',
    logo: 'https://example.com/logo.png',
    description: 'Example Ltd makes accessible project-management software for small teams.',
    foundingDate: '2015-04-01',
    email: 'hello@example.com',
    address: {
      streetAddress: '100 Market Street', addressLocality: 'Austin', addressRegion: 'TX', postalCode: '78701', addressCountry: 'US',
    },
    contactPoints: [{
      contactType: 'customer service', telephone: '+1 555 010 2030', email: 'support@example.com', areaServed: 'US', availableLanguage: 'English',
    }],
    sameAs: ['https://www.linkedin.com/company/example', 'https://x.com/example'],
  },
  copy: {
    keyword: 'organization schema generator',
    lead: 'This organization schema generator builds valid Organization JSON-LD for your company, charity or institution: name, logo, address, contact points and social profiles. It follows Google’s recommendations, including its logo guidelines.',
    tableIntro: 'Google lists no required properties for Organization markup. Instead it asks you to add as many as apply. The table groups them by how much they matter for identifying your organization.',
    mistakes: [
      'A logo that is too small or that cannot be crawled. Google asks for at least 112×112 pixels, a supported image format and a crawlable, indexable URL.',
      'A logo that looks wrong on a white background, such as white artwork with a transparent background. Check it on white.',
      'Putting a name that differs from the one you use everywhere else. The name should match your site name and other profiles.',
      'Adding Organization markup on every page. It is enough on the home page, or on an about or contact page, as long as it identifies the organization.',
      'A sameAs list of pages that are not about you. It should link only to profiles that represent the same organization.',
      'Inconsistent contact details between the markup, the page and your other listings.',
    ],
    notes: [
      'Organization markup is about identity: it tells Google that a name, a logo, a set of profiles and some contact details all belong to the same organization. That helps it connect your site to the entity behind it, and can influence the name and logo it shows.',
      'Google has removed some features that used to be associated with organization markup. Its structured data gallery no longer lists a sitelinks search box, so do not add markup for one. Focus on the identity properties: name, url, logo, sameAs and contact details.',
    ],
    example: 'A company with a logo, address, customer-service contact point and two social profiles, as generated on this page, is shown below.',
    faqs: [
      { q: 'Which properties are required for Organization schema?', a: 'Google lists none as required, and recommends including as many relevant ones as you can, such as name, url, logo, address, contact details and sameAs.' },
      { q: 'What size should the logo be?', a: 'At least 112×112 pixels, in a format Google Images supports, at a crawlable and indexable URL, and it should look right on a white background.' },
      { q: 'Where should I put Organization markup?', a: 'On your home page, and optionally on an about or contact page. It does not need to be on every page.' },
      { q: 'What is sameAs for?', a: 'It lists URLs of other pages that represent the same organization, such as social profiles and directory or encyclopedia entries, helping Google connect them.' },
      { q: 'Can I use it for a local shop?', a: 'For a business with a physical location, use LocalBusiness instead. It is a subtype of Organization and adds opening hours and coordinates.' },
    ],
  },
};
