/** Client-side PDF report (jsPDF, loaded only when the button is used). */
export async function downloadReport({ fileName, result }) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 48;
  const width = doc.internal.pageSize.getWidth() - margin * 2;
  let y = margin;
  const write = (text, { size = 10, bold = false, gap = 6 } = {}) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setFontSize(size);
    doc.splitTextToSize(String(text), width).forEach((line) => {
      if (y > 790) { doc.addPage(); y = margin; }
      doc.text(line, margin, y);
      y += size + 3;
    });
    y += gap;
  };
  write('ATS resume check report', { size: 18, bold: true, gap: 4 });
  write(`File: ${fileName}`);
  write(`Score: ${result.score} / 100`, { size: 14, bold: true });
  write('How the score is made: it starts at 100 and each issue below removes the points shown.');
  result.breakdown.forEach((item) => write(`-${item.penalty}  ${item.title}`, { gap: 2 }));
  y += 8;
  write('Issues and fixes', { size: 13, bold: true });
  if (!result.issues.length) write('No structural problems were found.');
  result.issues.forEach((item) => {
    write(`[${item.severity.toUpperCase()}] ${item.title}`, { bold: true, gap: 2 });
    write(item.explanation, { gap: 2 });
    write(`Fix: ${item.howToFix}`);
  });
  const e = result.entities;
  write('What an ATS-style parser extracted', { size: 13, bold: true });
  [['Name', e.name], ['Email', e.email], ['Phone', e.phone], ['LinkedIn', e.linkedin]].forEach(([label, value]) => write(`${label}: ${value || 'NOT FOUND'}`, { gap: 1 }));
  write(`Jobs found: ${e.jobs.length}`, { gap: 1 });
  e.jobs.forEach((job) => write(`  ${job.title || '(no title)'} at ${job.company || '(no company)'}, ${job.start} - ${job.end}`, { gap: 1 }));
  write(`Skills found: ${e.skills.join(', ') || 'none'}`);
  write('Generated by Talk & Tool. This is an approximation of how a typical parser reads a resume, not a simulation of any specific ATS.', { size: 8 });
  doc.save('ats-resume-report.pdf');
}
