export const SITE_URL = 'https://talkandtool.com';

export const premiumTools = [
  { slug: 'json-studio', title: 'JSON Formatter & Validator', shortTitle: 'JSON Formatter', description: 'Format, validate, and minify JSON online with clear syntax error messages. Your data is processed privately in your browser.', icon: '{}', category: 'Developer', tags: ['json', 'formatter', 'validator', 'beautifier'] },
  { slug: 'password-generator', title: 'Strong Password Generator', shortTitle: 'Password Generator', description: 'Generate secure random passwords with custom length, numbers, symbols, and letter options using your browser’s cryptographic generator.', icon: 'PW', category: 'Security', tags: ['password', 'security', 'random', 'generator'] },
  { slug: 'unit-converter', title: 'Free Online Unit Converter', shortTitle: 'Unit Converter', description: 'Convert length, weight, and digital storage units instantly with an accurate, easy-to-use online unit converter.', icon: '↔', category: 'Calculator', tags: ['unit', 'measurement', 'length', 'weight', 'convert'] },
  { slug: 'base64-tool', title: 'Base64 Encoder & Decoder', shortTitle: 'Base64 Tool', description: 'Encode text to Base64 or decode Base64 to readable Unicode text instantly and privately in your browser.', icon: '64', category: 'Developer', tags: ['base64', 'encode', 'decode', 'text'] },
  { slug: 'jwt-inspector', title: 'JWT Decoder & Inspector', shortTitle: 'JWT Decoder', description: 'Decode JWT headers and payload claims locally to inspect token contents and expiration without uploading your token.', icon: 'JWT', category: 'Security', tags: ['jwt', 'token', 'decoder', 'claims'] },
  { slug: 'timestamp-converter', title: 'Unix Timestamp Converter', shortTitle: 'Timestamp Converter', description: 'Convert Unix timestamps in seconds or milliseconds to local time, UTC, and ISO 8601 dates instantly.', icon: 'UTC', category: 'Developer', tags: ['unix', 'epoch', 'date', 'time'] },
  { slug: 'case-converter', title: 'Free Text Case Converter', shortTitle: 'Case Converter', description: 'Convert text to uppercase, lowercase, title case, camelCase, snake_case, or kebab-case instantly.', icon: 'Aa', category: 'Text', tags: ['case', 'text', 'camel', 'uppercase', 'lowercase'] },
  { slug: 'uuid-generator', title: 'Online UUID v4 Generator', shortTitle: 'UUID Generator', description: 'Generate one or many secure RFC 4122 version 4 UUIDs and GUIDs locally in your browser.', icon: '#', category: 'Developer', tags: ['uuid', 'guid', 'v4', 'generator'] },
  { slug: 'regex-tester', title: 'Online JavaScript Regex Tester', shortTitle: 'Regex Tester', description: 'Test JavaScript regular expressions online and see live matches, positions, flags, and pattern errors.', icon: '.*', category: 'Developer', tags: ['regex', 'regexp', 'javascript', 'pattern'] },
  { slug: 'word-counter', title: 'Free Word & Character Counter', shortTitle: 'Word Counter', description: 'Count words, characters, sentences, paragraphs, and estimated reading time instantly as you type.', icon: '123', category: 'Text', tags: ['word', 'character', 'sentence', 'reading time', 'counter'] },
  { slug: 'percentage-calculator', title: 'Free Percentage Calculator', shortTitle: 'Percentage Calculator', description: 'Calculate a percentage of a number, percentage change, increases, and decreases with clear formulas.', icon: '%', category: 'Calculator', tags: ['percentage', 'percent', 'increase', 'decrease', 'math'] },
  { slug: 'age-calculator', title: 'Exact Age Calculator', shortTitle: 'Age Calculator', description: 'Calculate exact age from a date of birth in years, months, and days, plus total days lived.', icon: 'DOB', category: 'Calculator', tags: ['age', 'birthday', 'date of birth', 'years', 'days'] },
  { slug: 'loan-calculator', title: 'Loan Payment & EMI Calculator', shortTitle: 'Loan Calculator', description: 'Estimate monthly loan payments, total interest, and total repayment from the loan amount, rate, and term.', icon: '$', category: 'Finance', tags: ['loan', 'emi', 'payment', 'interest', 'finance'] },
  { slug: 'bmi-calculator', title: 'BMI Calculator for Adults', shortTitle: 'BMI Calculator', description: 'Calculate adult body mass index from metric or US measurements and understand the standard BMI category.', icon: 'BMI', category: 'Health', tags: ['bmi', 'body mass index', 'weight', 'height', 'health'] },
  { slug: 'url-encoder', title: 'URL Encoder & Decoder', shortTitle: 'URL Encoder', description: 'Encode text for a URL or decode percent-encoded URL components safely and instantly in your browser.', icon: '%2F', category: 'Developer', tags: ['url', 'percent encoding', 'encode', 'decode', 'uri'] },
];

export const getToolBySlug = (slug) => premiumTools.find((tool) => tool.slug === slug);
